#!/bin/bash

# Apache
yum install -y httpd httpd-devel httpd-tools
chkconfig -add httpd
chkconfig httpd on
service httpd stop
rm -rf /var/www/html
ln -fs /vagrant /var/www/html
service httpd starti
# PHP
yum install -y php php-cli php-common php-devel php-mysql

